local char = game.Players.LocalPlayer.Character
-- char.Animate.walk.WalkAnim.AnimationId = "rbxassetid://74091760000804"
-- char.Animate.walk.WalkAnim.AnimationId = "rbxassetid://95855479602600"
-- char.Animate.walk.WalkAnim.AnimationId = "rbxassetid://89101204182562"
-- char.Animate.walk.WalkAnim.AnimationId = "rbxassetid://102149852882339"
-- char.Animate.walk.WalkAnim.AnimationId = "rbxassetid://95742464990478"
-- char.Animate.walk.WalkAnim.AnimationId = "rbxassetid://83943354517774"
-- char.Animate.walk.WalkAnim.AnimationId = "rbxassetid://93612655922136"
